name: ci

on:
  push:
    branches: [ main, part5-* ]
  pull_request:
  workflow_dispatch:

jobs:
  hadolint:
    name: Dockerfile Lint (Hadolint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: emulator/part3-containerization/Dockerfile
          failure-threshold: error    # <-- treat warnings as pass

  trivy-fs:
    name: Security Scan (Trivy - filesystem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan repository with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
