name: ci

on:
  push:
    branches: [ main, part5-* ]     # run CI on branch pushes
    tags: [ 'v*' ]                  # ALSO run when you push tags like v0.1.0
  pull_request:
  workflow_dispatch:

# needed to push images to GHCR using GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  hadolint:
    name: Dockerfile Lint (Hadolint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: emulator/part3-containerization/Dockerfile
          failure-threshold: error

  trivy-fs:
    name: Security Scan (Trivy - filesystem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan repository with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  arm64-build-smoke:
    name: ARM64 Buildx + Smoke
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU (arm64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (linux/arm64)
        uses: docker/build-push-action@v5
        with:
          context: emulator/part3-containerization
          file: emulator/part3-containerization/Dockerfile
          platforms: linux/arm64
          tags: local/retroarch:ci-arm64
          push: false
          load: true
      - name: Smoke test (retroarch --version)
        run: docker run --rm --platform linux/arm64 local/retroarch:ci-arm64 retroarch --version

  publish-ghcr:
    name: Publish to GHCR (arm64) on tag
    needs: [hadolint, trivy-fs, arm64-build-smoke]
    if: startsWith(github.ref, 'refs/tags/')   # only runs on tag pushes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU (arm64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (linux/arm64)
        uses: docker/build-push-action@v5
        with:
          context: emulator/part3-containerization
          file: emulator/part3-containerization/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/retroarch:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/retroarch:latest
